### ISSUE TITLE
Can't access ochem once running

### ISSUE THREAD

**Issue by JustAnotherRandomLad** [openochem/openochem#2]
I followed the installation instructions (using a VirtualBox VM), and I get this when I enter `bash startHostName.sh localhost`:

![image](https://user-images.githubusercontent.com/13906911/190943903-72bc7d90-996a-48f6-bdcc-a3025e2fbfff.png)

This happens when I follow the instructions to start the server manually:

![image](https://user-images.githubusercontent.com/13906911/190943956-0c40dcec-9cd6-4794-87c2-5b898134f863.png)

However, even an hour after doing either of these, trying to open `http://localhost:8080` or `http://localhost:7080/metaserver` results in a 404 error when done in the VM. (`http://localhost:7080` displays the default Apache Tomcat welcome screen.)
Meanwhile, all three of these `localhost` addresses produce this error when I try to open them on the host PC:
![image](https://user-images.githubusercontent.com/13906911/190944119-11ff94bc-bc29-4efe-a746-0d178d007faf.png)

Here are the logs for my latest VM session, in case they'll help.
[VBox.log](https://github.com/openochem/openochem/files/9595964/VBox.log)
[VBoxHardening.log](https://github.com/openochem/openochem/files/9595965/VBoxHardening.log)

I need this to work for the final step of my PhD research. Please respond at your earliest convenience.

**Comment by martin-sicho** [comment]
Hi @JustAnotherRandomLad,

it looks like the metaserver may have failed to start. There should be two (`*.out`) files in `./env/` folder (relative to where the `startHostName.sh` is located). Can you check if they are there and if there are any errors?

Also, you can alternatively deploy with docker (latest addition to `main`): https://github.com/openochem/openochem/tree/main/docker. Could be more straightforward.

**Comment by JustAnotherRandomLad** [comment]
Thank you for the response. Nothing jumps out at me as especially amiss in these .out files, but maybe you should have a look:
(I've changed their extensions to .txt to allow uploading here.)
[meta.txt](https://github.com/openochem/openochem/files/9601303/meta.txt)
[tomcat.txt](https://github.com/openochem/openochem/files/9601305/tomcat.txt)

**Comment by JustAnotherRandomLad** [comment]
@martin-sicho I took your advice and tried the Docker approach. Building was indeed much more straightforward, but now I get this when I try to open `http://localhost:8080`:
![image](https://user-images.githubusercontent.com/13906911/191648221-1383a9ad-b4c2-4200-84ff-732608f446a8.png)
(The support link leads to a 404.)

If it matters: for the most part, every second in the command prompt where I set things up, I get three warning messages saying "Access denied for user 'ochem'@'172.18.0.4' (using password: YES)". Not sure what this is about, considering I haven't been prompted for a password at any point, let alone entered one.

**Comment by martin-sicho** [comment]
> Thank you for the response. Nothing jumps out at me as especially amiss in these .out files, but maybe you should have a look: (I've changed their extensions to .txt to allow uploading here.) [meta.txt](https://github.com/openochem/openochem/files/9601303/meta.txt) [tomcat.txt](https://github.com/openochem/openochem/files/9601305/tomcat.txt)

These really seem not to tell much, but I would expect more information there. Usually, ochem outputs way more about its current configuration and things like that. Could be that the appropriate .war files did not get loaded on the classpath, but it is hard to tell. I do not have that much experience settings things up in a VM.

About the docker output, it seems there might be a problem in configuration. By default, the docker demo deployment should work without any passwords and should log you in as admin user by default so that access denied message is indeed amiss here. I will try to look into it and let you know if I can reproduce it. Did you run exactly the three commands mentioned in the docker [readme](https://github.com/openochem/openochem/tree/main/docker)?

One thing that jumps out at me now is the configuration in [`docker/cfg/metaserver.cfg`](https://github.com/openochem/openochem/blob/main/docker/cfg/metaserver.cfg). I believe it should be:

```
metaserver.maindb.{hibernate.connection.username} = root
metaserver.maindb.{hibernate.connection.password} =
```

So try to edit these two options like this and run `docker-compose -f docker/ochem-demo.yml build` again and make sure the `ochem` image gets updated (you can check with `docker images`).

EDIT: also remove the current containers you have with `docker-compose -f docker/ochem-demo.yml rm`

**Comment by JustAnotherRandomLad** [comment]
Yes, I used those exact three commands. I made that change to metaserver.cfg, removed the old containers, and re-ran the `build` and `up` commands as you described; the warning messages no longer appear, but I still get the same 500 error and stacktrace when trying to open localhost:8080.

**Comment by martin-sicho** [comment]
Well, that's at least one issue sorted :) Do you see any java stacktraces or errors in the output after the `up` command is issued (they can also be higher up in the output)? Look specifically for mentions of `Globals` since that was in the stacktrace the website shows so it should also be in the output somewhere, but in its entirety (unfortunately, what is shown on the website is incomplete). You can also refresh the website while looking at the output and maybe it will come up again.

In the meantime, I am trying the entire build and deployment from scratch so I will see if it comes up as well.

**Comment by JustAnotherRandomLad** [comment]
I've attached two parts of a typical output log. The second one in particular includes some lengthy error messages that sometimes appear when I try to open `localhost:8080`, but not always.
[ochem docker output log.txt](https://github.com/openochem/openochem/files/9631593/ochem.docker.output.log.txt)
[ochem docker output log 2.txt](https://github.com/openochem/openochem/files/9631747/ochem.docker.output.log.2.txt)

**Comment by martin-sicho** [comment]
I still see some database exceptions there (`ochem-demo     | java.sql.SQLSyntaxErrorException: Could not connect to address=(host=ochem-mariadb)(port=3306)(type=master) : (conn=1624) Unknown database 'metaserver_demo'`). Maybe it is corrupted or does not exist. You can try the following:

1. stop the instance (ctrl+c if attached to console or `docker-compose -f docker/ochem-demo.yml stop`)
2. `docker-compose -f docker/ochem-demo.yml rm` again
3. `docker volume prune` (should remove ochem volumes as well)
4. `docker-compose -f docker/ochem-demo.yml up` again -> it should now also reinitialize the database

Also, I just tried from scratch in a completely unrelated docker environment and it worked first try no issues. So I am still a little bit in the dark about what could be going on there, but the database errors are not good so definitely should be sorted. You can check if these steps remove them at least.

EDIT: You want to see the following output on the console when you execute `up` for the first time with no ochem volumes: 

```
ochem-mariadb  | DB Initialized.
ochem-mariadb  | aria_log.00000001
ochem-mariadb  | aria_log_control
ochem-mariadb  | ddl_recovery.log
ochem-mariadb  | fragment_demo
ochem-mariadb  | ib_buffer_pool
ochem-mariadb  | ib_logfile0
ochem-mariadb  | ibdata1
ochem-mariadb  | ibtmp1
ochem-mariadb  | metaserver_demo
ochem-mariadb  | multi-master.info
ochem-mariadb  | mysql
ochem-mariadb  | mysql_upgrade_info
ochem-mariadb  | ochem_demo
ochem-mariadb  | performance_schema
ochem-mariadb  | structures_demo
ochem-mariadb  | sys
```

**Comment by JustAnotherRandomLad** [comment]
This is the output log after I did as you instructed here:
[ochem docker output log new.txt](https://github.com/openochem/openochem/files/9633862/ochem.docker.output.log.new.txt)

I don't see the database exception you pointed out anymore, but I still get exactly the same 500 error page.

**Comment by JustAnotherRandomLad** [comment]
@martin-sicho I'm trying to make sense of this output log, though I'm not familiar enough with the program to know for sure which errors and warnings are normal and which aren't. I assume most of the ones about trying to open a file that doesn't exist are normal, given this is my first time using the program.

This stands out to me, though, as the first one that looks definitely wrong:
```
ochem-demo     | 59893 [org.springframework.scheduling.quartz.SchedulerFactoryBean#0_Worker-8] ERROR org.quartz.core.JobRunShell - Job DEFAULT.CleanAttachmentsDetail threw an unhandled Exception:
ochem-demo     | org.springframework.scheduling.quartz.JobMethodInvocationFailedException: Invocation of method 'executeInternal' on target class [class qspr.schedule.CleanAttachmentsTask] failed; nested exception is java.lang.NoClassDefFoundError: Could not initialize class qspr.Globals
ochem-demo     |        at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:320)
ochem-demo     |        at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:113)
ochem-demo     |        at org.quartz.core.JobRunShell.run(JobRunShell.java:216)
ochem-demo     |        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:549)
ochem-demo     | Caused by: java.lang.NoClassDefFoundError: Could not initialize class qspr.Globals
ochem-demo     |        at qspr.schedule.OchemCronjobTask.log(OchemCronjobTask.java:89)
ochem-demo     |        at qspr.schedule.OchemCronjobTask.executeInternal(OchemCronjobTask.java:69)
ochem-demo     |        at sun.reflect.GeneratedMethodAccessor58.invoke(Unknown Source)
ochem-demo     |        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
ochem-demo     |        at java.lang.reflect.Method.invoke(Method.java:498)
ochem-demo     |        at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:273)
ochem-demo     |        at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:311)
ochem-demo     |        ... 3 more
```

Many others of this format follow it, though they're not quite the same.

**Comment by martin-sicho** [comment]
@JustAnotherRandomLad Yes you are correct that this one is problematic, but there are actually more things that are off in the last log you sent (`ochem.docker.output.log.new.txt`). I also do not see the database initialization output I mentioned above anywhere and I see files missing that should be accessible (some missing link errors and such are OK, but I see more commands failing that should have gone through). I just did not have enough time to really dive deep into the log and take a look inside the image to find possible problems, but I will try to do so in the upcoming days.

By the way, on what platform are you trying to deploy? I have so far only used various Linux flavors so if it is something different or more esoteric it could be that something goes wrong during the build already...

**Comment by JustAnotherRandomLad** [comment]
Ah, that might be it. The VM from before was Ubuntu 22.04, but the host (on which I've been running Docker) is Windows 11.

**Comment by martin-sicho** [comment]
@JustAnotherRandomLad That might be it. I think there definitely could be some issues on Windows. From the output, it seems some files are missing in the created image so that leads me to believe the build process is to blame. I will try to build on Windows as well, but in the meantime you should definitely try it on Linux (Ubuntu and RHEL worked no problem so far).

**Comment by JustAnotherRandomLad** [comment]
@martin-sicho I've been wrestling with GPU issues in my Ubuntu VM trying to set up Docker. Any luck with Windows?

**Comment by JustAnotherRandomLad** [comment]
@martin-sicho I finally managed to get Ubuntu 22.04 directly on a computer, rather than on a VM. Now, it seems the `docker build` command (to which I need to add `sudo` - may have done something wrong installing Docker) is getting tripped up by `ModuleNotFoundError: No module named "torch"` - I thought the command was supposed to take care of any dependencies, yet it looks like PyTorch is an issue for it.
I installed it manually, but I'm still getting the same error.

**Comment by JustAnotherRandomLad** [comment]
I'm trying the regular installation method again (without Docker), and now this (eventually) happens when I try the `singularity build` command:
```
+ pip install haste_pytorch
Collecting haste_pytorch
  Downloading haste_pytorch-0.5.0rc0.tar.gz (44 kB)
     |████████████████████████████████| 44 kB 33 kB/s 
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-yn8bcbhb/haste-pytorch/setup.py'"'"'; __file__='"'"'/tmp/pip-install-yn8bcbhb/haste-pytorch/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-yn8bcbhb/haste-pytorch/pip-egg-info
         cwd: /tmp/pip-install-yn8bcbhb/haste-pytorch/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-yn8bcbhb/haste-pytorch/setup.py", line 58, in <module>
        from torch.utils import cpp_extension
    ModuleNotFoundError: No module named 'torch'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
FATAL:   While performing build: while running engine: exit status 1
```

**Comment by thegodone** [comment]
you can remove haste_pytorch we don't use it anymore

**Comment by JustAnotherRandomLad** [comment]
I commented out that line, and the build seems to have been successful - thank you. That said, now I'm back to exactly the same problem as when I first opened this issue (though it's not on a VM this time): https://github.com/openochem/openochem/issues/2#issue-1377336530

Here are the .out files this time (once again changed to .txt for uploading):
[meta.txt](https://github.com/openochem/openochem/files/9924589/meta.txt)
[tomcat.txt](https://github.com/openochem/openochem/files/9924590/tomcat.txt)

**Comment by thegodone** [comment]
Hi, what is your configuration, GPU or M1 mac ?

BR

**Comment by JustAnotherRandomLad** [comment]
Ubuntu 22.04, AMD64 architecture, set up on an external SSD. The GPU is NVIDIA GeForce RTX 2070 SUPER.
~~I'll edit this comment in a minute to add the rest of the specs.~~
Actually, I may have misunderstood you, sorry. I followed the installation instructions [here](https://github.com/openochem/openochem/blob/main/INSTRUCTIONS_OCHEM), for Ubuntu 22.04 on AMD64, using the MongoDB fix in step 2 (from Hayk in the linked AskUbuntu thread) and allowing connections outside localhost. I wasn't sure what step 3 (modules for mold2) was referring to, so I simply installed Mold2 itself within the root directory (EDIT: and made sure it would run); might that be relevant? (Also, judging by file locations, I presumed step 4 meant to say `cd ${ROOT_DIR}/singularity` rather than `cd ${ROOT_DIR}/demo-data`.)

I'm attaching the specs here, anyway, just in case:
![image](https://user-images.githubusercontent.com/13906911/199735889-085d19fa-0d05-4dee-96ea-727e7e71a5ee.png)

**Comment by thegodone** [comment]
@martin-sicho  can you have a look please ? I still not understand the issue with library path. This is not logical at all.

**Comment by JustAnotherRandomLad** [comment]
@martin-sicho Any ideas? I was able to complete the written thesis without this, but I'd still like to get it working to back up some of my findings.

**Comment by JustAnotherRandomLad** [comment]
@martin-sicho Following up one more time. I was able to complete my PhD without this, but would still like to get it working for the sake of a coming publication.

**Comment by thegodone** [comment]
Hi, can you try last docker build please.Instructions are in the readme in docker folder.It works on my mac max M1 configuration.Best Guillaume Envoyé de mon iPhoneLe 21 févr. 2023 à 20:26, JustAnotherRandomLad ***@***.***> a écrit :﻿
@martin-sicho Following up one more time. I was able to complete my PhD without this, but would still like to get it working for the sake of a coming publication.

**Comment by martin-sicho** [comment]
@JustAnotherRandomLad @thegodone Hi, very sorry for not getting back to you here. I was extremely busy and did not have an immediate access to a Windows machine to test the docker deployment on quickly. I now had to debug another issue on Windows and tried the whole deployment as well from start to finish. I think I was able to reproduce your issue, @JustAnotherRandomLad. I got similar error to the one you cite above, mainly this part was the same:

```
nested exception is java.lang.NoClassDefFoundError: Could not initialize class qspr.Globals
```

I tracked it down to the database not being initialized initially. I changed the deployment script to wait for 60 seconds before anything is done to give the DB image enough time to initialize. Specifically, look for this output:

```
ochem-mariadb  | DB Initialized.
ochem-mariadb  | aria_log.00000001
ochem-mariadb  | aria_log_control
ochem-mariadb  | ddl_recovery.log
ochem-mariadb  | fragment_demo
ochem-mariadb  | ib_buffer_pool
ochem-mariadb  | ib_logfile0
ochem-mariadb  | ibdata1
ochem-mariadb  | ibtmp1
ochem-mariadb  | metaserver_demo
ochem-mariadb  | multi-master.info
ochem-mariadb  | mysql
ochem-mariadb  | mysql_upgrade_info
ochem-mariadb  | ochem_demo
ochem-mariadb  | performance_schema
ochem-mariadb  | structures_demo
ochem-mariadb  | sys
```

If this runs before OChem deploys for the first time, everything should be fine. You can also check with any SQL client if the tables exist in the `ochem_demo` database. In the demo, the DB runs on your `localhost:3306` and you can connect to it with the `root` account without a password. You can check at the following URLs if everything is working:

```
localhost:8080 # web frontend
localhost:7080 # metaserver
```

**Comment by JustAnotherRandomLad** [comment]
Thank you for the response. I tried setting up the new Docker build. I now get this error when trying to connect to localhost:8080...
![image](https://user-images.githubusercontent.com/13906911/220751824-0da04cf4-cea0-4c18-b512-1b852b302811.png)

...and a page containing this text when trying to connect to localhost:7080/metaserver:
[7080 metaserver error.txt](https://github.com/openochem/openochem/files/10808079/7080.metaserver.error.txt)

I don't see the ochem-mariadb output lines, but I do see a line like this appearing every second (with varying starting and HelperThread numbers):
```
ochem-demo     | 754906 [C3P0PooledConnectionPoolManager[identityToken->z8kfltauy2i3bzpeh9zp|5a95aaae]-HelperThread-#1] WARN org.mariadb.jdbc.message.server.ErrorPacket - Error: 1049-42000: Unknown database 'metaserver_demo'
```

**Comment by openochem** [comment]
This can be due to old version of flyway database. The solution is mentioned in docker installation readme file:

N.B.! If you upgrade from the previous version, delete flyway_schema_history table in ochem_demo and restart the docker:

docker exec ochem-mariadb mariadb ochem_demo -e "drop table flyway_schema_history"

**Comment by JustAnotherRandomLad** [comment]
That command just gets me this message:
`ERROR 1049 (42000): Unknown database 'ochem_demo'`

**Comment by openochem** [comment]
OK, the problem is another one. It means that mariadb database was not initialised at all.  Thus login to database docker and reinstall it manually:

docker exec -it ochem-mariadb /bin/bash
gunzip *.gz
bash insert_databases.sh 

and restart docker.

**Comment by JustAnotherRandomLad** [comment]
This is what I get when I run those commands:
```
root@76eef4ec2817:/ochem/demo-data# gunzip *.gz
gzip: *.gz: No such file or directory
root@76eef4ec2817:/ochem/demo-data# bash insert_databases.sh
gzip: *.gz: No such file or directory
ERROR 1007 (HY000) at line 3: Can't create database 'metaserver_demo'; database exists
```
Docker crashed trying to restart, but I've finally managed to reach the main page on `localhost:8080`. Progress! I'll let you know if there are any further issues from here.

**Comment by JustAnotherRandomLad** [comment]
Things seem to be running smoothly at last. (That said, I'd hoped to calculate Dragon descriptors with this and don't see them as an option here, but that's a completely separate issue.)

Thank you for all the help!

**Comment by thegodone** [comment]
Indeed, Dragon is not free tool, so you need a license. An alternative is
to use RDKit 3D descriptors.

**Comment by JustAnotherRandomLad** [comment]
Considering Dragon has been discontinued, is there any way for me to obtain a license now, or any other way to set up calculation of those descriptors?

**Comment by openochem** [comment]
The descriptors can be used to develop models at  https://ochem.eu  (but not downloaded due to agreement we have with Dragon developers) or, in case if one still have Java based browser, can be calculated and downloaded at http://vcclab.org. alvaDesc are developed by Andrea Mauri, de facto contain all Dragon descriptors and can be calculated and downloaded at https://ochem.eu. Contact Andrea at Alvascience for a commercial version.
